name: NuGet Push

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Dotnet for use with actions
      uses: actions/setup-dotnet@v1.0.0
    - name: Build with dotnet
      run: dotnet build --configuration Release
    #- name: Test with dotnet
    #  run: dotnet test
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Pack with dotnet
        run: dotnet pack --configuration Release
      - name: Push to nuget with dotnet
        run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_DEPLOY_KEY }} --source https://api.nuget.org/v3/index.json -no-symbols true
    
